export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const LOADING = 'LOADING'
export const LOCATE_ADDRESS = 'LOCATE_ADDRESS'
export const START_SUGGEST_ADDRESS = 'START_SUGGEST_ADDRESS'
export const END_SUGGEST_ADDRESS = 'END_SUGGEST_ADDRESS'

export const AUTH_CLEAR = 'AUTH_CLEAR'
export const START_AUTH = 'START_AUTH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const LOG_OUT = 'LOG_OUT'

export const SET_HOME_COORDS = 'SET_HOME_COORDS'
export const SET_RESTURANT_COORDS = 'SET_RESTURANT_COORDS'
export const SET_SIGNUP_COORDS = 'SET_SIGNUP_COORDS'

export const SET_CART = 'SET_CART'
export const CART_LOADING = 'CART_LOADING'
export const EMPTY_CART = 'EMPTY_CART'
export const TOGGLE_ITEM = 'TOGGLE_ITEM'
export const INC_ITEM = 'INC_ITEM'
export const DEC_ITEM = 'DEC_ITEM'

export const GET_MENU_ITEM_FORM = 'GET_MENU_ITEM_FORM'
export const GET_MENU_FORM = 'GET_MENU_FORM'
export const GET_MENU_REVIEW_FORM = 'GET_MENU_REVIEW_FORM'

export const SET_ERROR_ON = 'SET_ERROR_ON'
export const SET_ERROR_OFF = 'SET_ERROR_OFF'

// export const SET_MENU = 'SET_MENU'
// export const ADD = 'ADD'
// export const REMOVE = 'REMOVE'
// export const ADD_ITEM = 'ADD_ITEM'
// export const REMOVE_ITEM = 'REMOVE_ITEM'
