export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const LOADING = 'LOADING'
export const LOCATE_ADDRESS = 'LOCATE_ADDRESS'
export const START_SUGGEST_ADDRESS = 'START_SUGGEST_ADDRESS'
export const END_SUGGEST_ADDRESS = 'END_SUGGEST_ADDRESS'

export const SET_MENU = 'SET_MENU'
export const ADD = 'ADD'
export const REMOVE = 'REMOVE'
export const ADD_ITEM = 'ADD_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
